spring.application.name=ms-barriodigital-requests
server.port=${SERVER_PORT:8081}

spring.config.import=optional:file:.env[.properties],optional:file:./barriodigitalrequests/.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

server.error.include-stacktrace=never
server.error.include-message=never